name: infosumbar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  google_fonts: 3.0.1
  flutter: 
    sdk: flutter
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  google_sign_in: ^5.3.3
  flutter_svg: ^1.1.0
  animate_do: ^2.1.0
  internet_connection_checker: ^0.0.1+4
  lottie: ^1.3.0
  cloud_firestore: ^3.1.17
  zoom_pinch_overlay: ^1.2.0
  firebase_storage: ^10.2.17
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  shimmer: ^2.0.0
  introduction_slider: ^1.0.0
  go_router: ^4.0.0
 
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets: 
    - assets/
  uses-material-design: true

